"""Locating a buried phone, tested against a target we placed ourselves.

Ground truth is generated by running the same path-loss model FORWARD - pick a true
position, compute the RSSI each receiver would see, then check the estimator recovers it.
That does not prove the model matches real debris (nothing here can); it proves the
arithmetic and the geometry are right, which is the part that must be right before the
model is worth arguing about.
"""
from __future__ import annotations

import math

import pytest

from pahiro.locate import (DEBRIS_N, PositionEstimate, Reading, estimate_position,
                           rssi_to_distance, search_radius_for)

TX = -59.0


def rssi_at(distance_m: float, n: float = 2.0) -> float:
    return TX - 10.0 * n * math.log10(max(distance_m, 1.0))


def test_rssi_to_distance_inverts_the_model():
    for d in (1.0, 5.0, 20.0, 100.0, 400.0):
        assert rssi_to_distance(rssi_at(d), TX, 2.0) == pytest.approx(d, rel=0.02)


def test_a_signal_stronger_than_the_reference_is_clamped_not_negative():
    """Standing on top of the device should not produce a negative distance."""
    assert rssi_to_distance(-10.0, TX, 2.0) == 1.0


def test_three_receivers_recover_a_position():
    lat0, lon0 = 27.7600, 85.0500
    target = (27.7620, 85.0535)
    receivers = [("r1", 27.7600, 85.0500), ("r2", 27.7640, 85.0520), ("r3", 27.7605, 85.0560)]

    readings = []
    for label, rlat, rlon in receivers:
        d = math.dist(_plane(rlat, rlon, lat0, lon0), _plane(*target, lat0, lon0))
        readings.append(Reading(lat=rlat, lon=rlon, rssi_dbm=rssi_at(d), label=label))

    est = estimate_position(readings)
    assert est.method == "weighted-least-squares"
    assert est.receivers == 3
    err = math.dist(_plane(est.lat, est.lon, lat0, lon0), _plane(*target, lat0, lon0))
    assert err < 25, f"estimated {err:.1f} m from the true position"
    assert est.confidence in ("high", "medium")
    assert est.radius_m >= 15.0, "a search radius is always reported"


def _plane(lat: float, lon: float, lat0: float, lon0: float) -> tuple[float, float]:
    from pahiro.locate import _to_plane
    return _to_plane(lat, lon, lat0, lon0)


def test_one_receiver_gives_a_circle_and_says_it_cannot_give_a_direction():
    est = estimate_position([Reading(lat=27.7, lon=85.0, rssi_dbm=-70, label="r1")])
    assert est.confidence == "low"
    assert est.method == "single-receiver-proximity"
    assert "Move and read again" in " ".join(est.notes)


def test_two_receivers_refuse_to_triangulate():
    """Two circles meet in two places. Inventing one of them sends a team to the wrong
    spot, so this returns a bearing and says so."""
    est = estimate_position([
        Reading(lat=27.7600, lon=85.0500, rssi_dbm=-65, label="r1"),
        Reading(lat=27.7640, lon=85.0520, rssi_dbm=-80, label="r2"),
    ])
    assert est.method == "two-receiver-bearing"
    assert est.bearing_deg is not None
    assert est.confidence == "low"
    assert "cannot resolve a position" in " ".join(est.notes)


def test_collinear_receivers_are_reported_not_solved():
    """Receivers in a line carry no information perpendicular to it. A singular matrix
    must become an honest answer, not a coordinate."""
    est = estimate_position([
        Reading(lat=27.7600, lon=85.0500, rssi_dbm=-70, label="a"),
        Reading(lat=27.7620, lon=85.0500, rssi_dbm=-75, label="b"),
        Reading(lat=27.7640, lon=85.0500, rssi_dbm=-80, label="c"),
    ])
    assert est.method == "collinear-receivers"
    assert "in a line" in " ".join(est.notes)


def test_noise_widens_the_search_area_rather_than_moving_the_centre():
    """A rescue decision is 'how big an area', so noise must show up as radius."""
    lat0, lon0 = 27.76, 85.05
    receivers = [(27.7600, 85.0500), (27.7640, 85.0520), (27.7605, 85.0560)]
    target = (27.7620, 85.0535)

    clean, noisy = [], []
    for i, (rlat, rlon) in enumerate(receivers):
        d = math.dist(_plane(rlat, rlon, lat0, lon0), _plane(*target, lat0, lon0))
        clean.append(Reading(lat=rlat, lon=rlon, rssi_dbm=rssi_at(d), label=f"r{i}"))
        noisy.append(Reading(lat=rlat, lon=rlon,
                             rssi_dbm=rssi_at(d) + (6.0 if i == 1 else -4.0), label=f"r{i}"))

    a, b = estimate_position(clean), estimate_position(noisy)
    assert b.radius_m > a.radius_m, "noise must widen the area"
    assert b.residual_m > a.residual_m


def test_debris_model_admits_the_distance_is_under_estimated():
    """The honest note: assuming free air makes the distance too long, which keeps the
    person inside the search area rather than outside it."""
    est = estimate_position([
        Reading(lat=27.7600, lon=85.0500, rssi_dbm=-65),
        Reading(lat=27.7640, lon=85.0520, rssi_dbm=-72),
        Reading(lat=27.7605, lon=85.0560, rssi_dbm=-78),
    ])
    assert any("free air" in n for n in est.notes)
    # the same RSSI means a shorter distance under debris
    assert rssi_to_distance(-80, TX, DEBRIS_N) < rssi_to_distance(-80, TX, 2.0)


def test_search_radius_grows_with_signal_noise():
    assert search_radius_for(2.0, 50.0, 2.0) < search_radius_for(2.0, 50.0, 8.0)


def test_no_readings_is_not_a_position():
    est = estimate_position([])
    assert est.lat is None and est.method == "no-signal"
