/// The Bluetooth-advertisement beacon codec, in Dart.
///
/// This is the SAME wire format as `src/pahiro/mesh/beacon.py` (Python) and
/// `web/public/field/beacon.js` (JavaScript): same 20 bytes, same field offsets, same FNV-1a
/// truncation, same CRC-8/ATM, same relay rule. Three implementations of one radio format is
/// three chances to disagree, so the agreement is checked rather than trusted -
/// `test/beacon_test.dart` asserts the exact bytes against vectors generated by the Python.
///
/// A disagreement on a radio format is worse than a parse error. It is a frame the other side
/// decodes into a different position, or fails to recognise as a duplicate and reports twice.
///
/// Web Bluetooth cannot advertise, and neither can a browser at all. A Flutter app CAN, which is
/// the reason this port exists: `canAdvertise` is true here and false on the web, and the
/// difference is the whole argument for shipping a native build.
library;

import 'dart:convert';
import 'dart:typed_data';

const int wireVersion = 1;

/// The payload we control inside a legacy advertising packet:
///   31  total legacy advertising payload
///   -3  the Flags AD structure a discoverable advertiser must include
///   -1  our AD structure's length byte
///   -1  our AD structure's type byte (0xFF, manufacturer specific)
///   -2  the manufacturer company identifier
///   =24
const int maxAdBytes = 24;

/// Twenty of those twenty-four are used. Four are left unallocated on purpose.
const int encodedBytes = 20;

const int kindSos = 0;
const int kindBeacon = 1;
const int kindStatus = 2;
const Map<int, String> kindNames = {0: 'sos', 1: 'beacon', 2: 'status'};
const Map<String, int> kindValues = {'sos': 0, 'beacon': 1, 'status': 2};

const List<String> severities = ['info', 'concern', 'urgent', 'critical'];

const int maxTtl = 7; // 3 bits, matching DEFAULT_TTL in the Python protocol
const int maxHops = 7; // 3 bits
const int maxPeople = 15; // 4 bits; 15 means "15 or more"
const int ageBucketSeconds = 300; // 5 minutes

const int flagHasPosition = 0x01;
const int flagLowBattery = 0x02;

const int posScale = 100000; // 1e-5 degrees

/// A frame that must not be emitted, because it would decode as something else.
class BeaconError implements Exception {
  final String message;
  BeaconError(this.message);
  @override
  String toString() => 'BeaconError: $message';
}

/// A decoded advertisement, before it is expanded into a mesh message.
class Beacon {
  final int dev16;
  final int msgId16;
  final String kind;
  final int ttl;
  final int hops;
  final String severity;

  /// 0 = unknown, 1..14 = count, 15 = "15 or more".
  final int people;
  final double? lat;
  final double? lon;
  final DateTime created;
  final bool lowBattery;

  const Beacon({
    required this.dev16,
    required this.msgId16,
    required this.kind,
    required this.ttl,
    required this.hops,
    required this.severity,
    required this.people,
    required this.lat,
    required this.lon,
    required this.created,
    required this.lowBattery,
  });

  bool get hasPosition => lat != null && lon != null;

  String get peopleText {
    if (people == 0) return 'unknown number of people';
    if (people >= maxPeople) return '$maxPeople+ people';
    return people == 1 ? '1 person' : '$people people';
  }

  String get origin => 'dev-${hex4(dev16)}';
  String get messageId => 'beacon-${hex4(msgId16)}';

  double ageSeconds([DateTime? now]) =>
      ((now ?? DateTime.now().toUtc()).difference(created)).inMilliseconds / 1000.0;

  /// A frame from the future is stale, not fresh - a wrong clock is not a rescue.
  bool isStale({double maxAgeSeconds = 6 * 3600, DateTime? now}) {
    final age = ageSeconds(now);
    return age < 0 || age > maxAgeSeconds;
  }
}

String hex4(int n) => n.toRadixString(16).padLeft(4, '0');

/// FNV-1a, 32-bit, folded to 16 by XOR of the halves.
///
/// Not blake2s, which was the first choice and had to go: the browser cannot compute it, so a
/// JavaScript phone and a Python gateway would truncate the same name to different bits and
/// disagree about what was a duplicate. The same reasoning applies with more force here - this
/// is a truncation for dedupe, not a security property.
int truncate16(Object value) {
  final bytes = utf8.encode(value.toString());
  var h = 0x811C9DC5;
  for (final b in bytes) {
    h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF;
  }
  return (h ^ (h >> 16)) & 0xFFFF;
}

/// CRC-8/ATM, polynomial 0x07, init 0x00 - byte for byte the Python implementation.
int crc8(List<int> data) {
  var crc = 0x00;
  for (final byte in data) {
    crc ^= byte;
    for (var i = 0; i < 8; i++) {
      crc = (crc & 0x80) != 0 ? ((crc << 1) ^ 0x07) & 0xFF : (crc << 1) & 0xFF;
    }
  }
  return crc;
}

int bucketOf(DateTime when) =>
    (when.toUtc().millisecondsSinceEpoch ~/ 1000 ~/ ageBucketSeconds) & 0xFFFFFFFF;

DateTime unbucket(int bucket) => DateTime.fromMillisecondsSinceEpoch(
      bucket * ageBucketSeconds * 1000,
      isUtc: true,
    );

/// Build a frame from raw 16-bit identifiers.
///
/// Split out from [encode] because a relay holds only the truncated bits: it must rebuild the
/// frame it received without knowing the strings those bits came from.
Uint8List pack(
  int dev16,
  int msg16, {
  String kind = 'sos',
  double? lat,
  double? lon,
  int ttl = maxTtl,
  int hops = 0,
  String severity = 'urgent',
  int people = 0,
  bool lowBattery = false,
  DateTime? when,
}) {
  if (!kindValues.containsKey(kind)) {
    throw BeaconError('unknown kind $kind');
  }
  if (!severities.contains(severity)) {
    throw BeaconError('unknown severity $severity');
  }
  if (ttl < 0 || ttl > maxTtl) throw BeaconError('ttl $ttl outside 0..$maxTtl');
  if (hops < 0 || hops > maxHops) throw BeaconError('hops $hops outside 0..$maxHops');
  if (people < 0 || people > maxPeople) {
    throw BeaconError('people $people outside 0..$maxPeople');
  }
  if ((lat == null) != (lon == null)) {
    throw BeaconError('latitude and longitude must be given together or not at all');
  }
  if (lat != null && (lat < -90.0 || lat > 90.0)) {
    throw BeaconError('latitude $lat out of range');
  }
  if (lon != null && (lon < -180.0 || lon > 180.0)) {
    throw BeaconError('longitude $lon out of range');
  }

  var flags = 0;
  if (lat != null) flags |= flagHasPosition;
  if (lowBattery) flags |= flagLowBattery;

  final out = BytesBuilder();
  out.addByte((wireVersion << 5) | (kindValues[kind]! << 2) | flags);
  out.add(_u16(dev16 & 0xFFFF));
  out.add(_u16(msg16 & 0xFFFF));
  out.addByte(((ttl & 0x07) << 5) |
      ((hops & 0x07) << 2) |
      severities.indexOf(severity));
  out.addByte((people & 0x0F) << 4); // low nibble reserved, written as zero

  if (lat == null) {
    out.add(Uint8List(8));
  } else {
    out.add(_i32((lat * posScale).round()));
    out.add(_i32((lon! * posScale).round()));
  }
  out.add(_u32(bucketOf(when ?? DateTime.now().toUtc())));

  final body = out.toBytes();
  if (body.length != encodedBytes - 1) {
    throw BeaconError('layout and encoder have drifted apart: ${body.length}');
  }
  return Uint8List.fromList([...body, crc8(body)]);
}

/// Pack a distress frame, hashing the identifiers down to the 16 bits that fit.
Uint8List encode(
  Object deviceId,
  Object msgId, {
  String kind = 'sos',
  double? lat,
  double? lon,
  int ttl = maxTtl,
  int hops = 0,
  String severity = 'urgent',
  int people = 0,
  bool lowBattery = false,
  DateTime? when,
}) =>
    pack(
      truncate16(deviceId),
      truncate16(msgId),
      kind: kind,
      lat: lat,
      lon: lon,
      ttl: ttl,
      hops: hops,
      severity: severity,
      people: people,
      lowBattery: lowBattery,
      when: when,
    );

/// Read a frame back. Returns null for anything that is not a valid beacon.
///
/// Null rather than an exception, because this runs on every advertisement a scanner hears: a
/// phone in a market hears hundreds a minute from earbuds, tags and watches, and every one of
/// them lands here. A decoder that threw would make the scanner unusable, and one that guessed
/// would turn a pair of earbuds into a landslide victim.
Beacon? decode(List<int>? payload) {
  if (payload == null) return null;
  if (payload.length != encodedBytes) return null;
  final data = payload is Uint8List ? payload : Uint8List.fromList(payload);

  if (crc8(data.sublist(0, encodedBytes - 1)) != data[encodedBytes - 1]) return null;

  final header = data[0];
  if ((header >> 5) != wireVersion) return null;
  final kind = kindNames[(header >> 2) & 0x07];
  if (kind == null) return null;
  final flags = header & 0x03;

  final dev16 = _readU16(data, 1);
  final msg16 = _readU16(data, 3);
  final timing = data[5];
  final ttl = (timing >> 5) & 0x07;
  final hops = (timing >> 2) & 0x07;
  final severity = severities[timing & 0x03];
  final people = (data[6] >> 4) & 0x0F;

  double? lat;
  double? lon;
  if ((flags & flagHasPosition) != 0) {
    lat = _readI32(data, 7) / posScale;
    lon = _readI32(data, 11) / posScale;
  }

  return Beacon(
    dev16: dev16,
    msgId16: msg16,
    kind: kind,
    ttl: ttl,
    hops: hops,
    severity: severity,
    people: people,
    lat: lat,
    lon: lon,
    created: unbucket(_readU32(data, 15)),
    lowBattery: (flags & flagLowBattery) != 0,
  );
}

/// Decode, spend one hop, re-encode. Null when invalid or out of hops.
///
/// Every field except ttl and hops is preserved byte for byte: a relay that "improved" the
/// coordinates would be inventing a rescue location it never measured, and one that changed the
/// ids would defeat dedupe across paths of different length.
Uint8List? relay(List<int> payload) {
  final b = decode(payload);
  if (b == null || b.ttl <= 0) return null;
  return pack(
    b.dev16,
    b.msgId16,
    kind: b.kind,
    lat: b.lat,
    lon: b.lon,
    ttl: b.ttl - 1,
    hops: b.hops + 1 > maxHops ? maxHops : b.hops + 1,
    severity: b.severity,
    people: b.people,
    lowBattery: b.lowBattery,
    when: b.created,
  );
}

/// A Flutter app CAN put bytes on the air. A browser cannot. That difference is the argument
/// for the native build, so it is recorded here rather than implied.
const bool canAdvertise = true;

// ---- big-endian primitives ------------------------------------------------------------------

Uint8List _u16(int v) => Uint8List.fromList([(v >> 8) & 0xFF, v & 0xFF]);

Uint8List _u32(int v) => Uint8List.fromList([
      (v >> 24) & 0xFF,
      (v >> 16) & 0xFF,
      (v >> 8) & 0xFF,
      v & 0xFF,
    ]);

Uint8List _i32(int v) {
  final u = v & 0xFFFFFFFF;
  return Uint8List.fromList([
    (u >> 24) & 0xFF,
    (u >> 16) & 0xFF,
    (u >> 8) & 0xFF,
    u & 0xFF,
  ]);
}

int _readU16(Uint8List d, int o) => (d[o] << 8) | d[o + 1];

int _readU32(Uint8List d, int o) =>
    ((d[o] << 24) | (d[o + 1] << 16) | (d[o + 2] << 8) | d[o + 3]) & 0xFFFFFFFF;

/// Signed 32-bit: Dart ints do not wrap, so the sign is applied explicitly.
int _readI32(Uint8List d, int o) {
  final v = _readU32(d, o);
  return v >= 0x80000000 ? v - 0x100000000 : v;
}

String hexOf(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
